"""Plan-only Claude Fable 5 runner for Hermes slash commands."""

from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any


FABLE_PROVIDER = "anthropic"
FABLE_MODEL = "claude-fable-5"
FABLE_ROUTE = "anthropic_oauth"
FABLE_TRANSPORT = "anthropic_oauth"
FABLE_REASONING = {"enabled": True, "effort": "high"}

FABLE_PLAN_SYSTEM_PROMPT = """You are Claude Fable 5 running inside Hermes as a plan-only command.

Generate a Markdown implementation plan only. Do not edit files, create branches,
open pull requests, deploy, or claim that any implementation has happened.

The plan must include these sections:
- Goal
- Current Context and Assumptions
- Proposed Approach
- Step-by-Step Plan
- Files Likely to Change
- Tests and Validation
- Risks and Open Questions

State clearly that this is a plan generated by Claude Fable 5 via Hermes `/fable`.
Keep the plan concrete and actionable, but do not include fabricated completion
status, commits, PRs, deployments, or test results.
"""


@dataclass(frozen=True)
class FablePlanRequest:
    prompt: str
    session_id: str = ""
    workdir: str = ""
    source_text: str = ""
    platform: str = ""
    transport: str = FABLE_TRANSPORT
    max_tokens: int = 12000
    timeout_seconds: int = 300


@dataclass(frozen=True)
class FablePlanResult:
    ok: bool
    content: str
    transport: str
    model: str
    error: str = ""
    refusal: bool = False


def fable_metadata(result: FablePlanResult | None = None) -> dict[str, Any]:
    metadata = {
        "command": "fable",
        "plan_artifact_kind": "fable_plan",
        "response_kind": "fable_plan",
        "kind": "fable_plan",
        "transport": FABLE_TRANSPORT,
        "provider": FABLE_PROVIDER,
        "model": FABLE_MODEL,
    }
    if result is not None:
        metadata["transport"] = result.transport
        metadata["model"] = result.model
        metadata["ok"] = result.ok
        metadata["refusal"] = result.refusal
    return metadata


def build_fable_context_packet(request: FablePlanRequest) -> str:
    sections = [
        ("User Request", request.prompt.strip()),
        ("Plan-Only Contract", "Generate a Markdown plan only. Do not edit files, open PRs, deploy, or claim implementation."),
        ("Session", request.session_id.strip()),
        ("Platform", request.platform.strip()),
        ("Workdir", request.workdir.strip()),
        ("Source Text", request.source_text.strip()),
    ]

    workdir = Path(request.workdir).expanduser() if request.workdir else None
    if workdir and workdir.exists() and workdir.is_dir():
        sections.extend(_workspace_context_sections(workdir))

    rendered: list[str] = []
    for title, value in sections:
        if value:
            rendered.append(f"## {title}\n{value.strip()}")
    return "\n\n".join(rendered).strip()


def generate_fable_plan(request: FablePlanRequest, config: dict[str, Any] | None = None) -> FablePlanResult:
    cfg = _fable_config(config)
    if cfg.get("enabled") is False:
        return _error("/fable is disabled in Hermes config.")
    if str(cfg.get("provider") or FABLE_PROVIDER).strip().lower() != FABLE_PROVIDER:
        return _error("/fable is pinned to provider=anthropic; configured provider is unsupported.")
    if str(cfg.get("model") or FABLE_MODEL).strip() != FABLE_MODEL:
        return _error("/fable is pinned to model=claude-fable-5; configured model is unsupported.")
    if str(cfg.get("route") or FABLE_ROUTE).strip().lower() != FABLE_ROUTE:
        return _error("/fable is pinned to route=anthropic_oauth; configured route is unsupported.")
    if request.transport != FABLE_TRANSPORT:
        return _error("/fable only supports Hermes' Anthropic OAuth route.")

    max_tokens = _positive_int(cfg.get("max_tokens"), request.max_tokens)
    timeout_seconds = _positive_int(cfg.get("timeout_seconds"), request.timeout_seconds)
    return _generate_via_anthropic_oauth(
        FablePlanRequest(
            prompt=request.prompt,
            session_id=request.session_id,
            workdir=request.workdir,
            source_text=request.source_text,
            platform=request.platform,
            transport=request.transport,
            max_tokens=max_tokens,
            timeout_seconds=timeout_seconds,
        )
    )


def _generate_via_anthropic_oauth(request: FablePlanRequest) -> FablePlanResult:
    try:
        from agent.auxiliary_client import resolve_provider_client

        client, resolved_model = resolve_provider_client(FABLE_PROVIDER, FABLE_MODEL)
    except Exception as exc:
        return _error(f"Fable 5 is not configured through Hermes' Anthropic OAuth route: {exc}")

    if client is None or not resolved_model:
        return _error(
            "Fable 5 is not configured through Hermes' Anthropic OAuth route. "
            "Run `hermes auth add anthropic` or configure the Anthropic OAuth provider used by Hermes."
        )
    if str(resolved_model) != FABLE_MODEL:
        return _error(f"Fable route resolved unexpected model {resolved_model!r}; refusing to fall back.")

    try:
        response = client.chat.completions.create(
            model=FABLE_MODEL,
            messages=[
                {"role": "system", "content": FABLE_PLAN_SYSTEM_PROMPT},
                {"role": "user", "content": build_fable_context_packet(request)},
            ],
            max_tokens=request.max_tokens,
            timeout=request.timeout_seconds,
            extra_body={"reasoning": FABLE_REASONING},
        )
    except Exception as exc:
        return _error(f"Fable 5 request failed on Hermes' Anthropic OAuth route: {exc}")

    choice = (getattr(response, "choices", None) or [None])[0]
    finish_reason = str(getattr(choice, "finish_reason", "") or "").lower()
    content = _extract_choice_content(choice).strip()
    if finish_reason == "refusal":
        return FablePlanResult(False, content, FABLE_TRANSPORT, FABLE_MODEL, "Fable refused this request.", refusal=True)
    if not content or len(content) < 40:
        return _error("Fable 5 returned an empty or too-short plan; refusing to post junk output.")
    return FablePlanResult(True, _ensure_plan_disclaimer(content), FABLE_TRANSPORT, FABLE_MODEL)


def _extract_choice_content(choice: Any) -> str:
    message = getattr(choice, "message", None)
    content = getattr(message, "content", "") if message is not None else ""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts: list[str] = []
        for item in content:
            if isinstance(item, dict):
                text = item.get("text") or item.get("content")
                if isinstance(text, str):
                    parts.append(text)
        return "".join(parts)
    return str(content or "")


def _ensure_plan_disclaimer(content: str) -> str:
    marker = "Generated by Claude Fable 5 via Hermes `/fable`. This is a plan only; no implementation was performed."
    if "no implementation" in content.lower() or "plan only" in content.lower():
        return content.strip()
    return f"{content.strip()}\n\n> {marker}"


def _workspace_context_sections(workdir: Path) -> list[tuple[str, str]]:
    sections: list[tuple[str, str]] = []
    for rel in ("AGENTS.md", "docs/project-state.md", "docs/context.md"):
        path = workdir / rel
        if path.is_file():
            sections.append((rel, _read_excerpt(path)))
    git_summary = _git_summary(workdir)
    if git_summary:
        sections.append(("Git Summary", git_summary))
    return sections


def _read_excerpt(path: Path, limit: int = 6000) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    return text[:limit]


def _git_summary(workdir: Path) -> str:
    if not (workdir / ".git").exists():
        return ""
    env = os.environ.copy()
    env.pop("GIT_DIR", None)
    env.pop("GIT_WORK_TREE", None)
    commands = [
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        ["git", "rev-parse", "--short", "HEAD"],
        ["git", "status", "--short"],
    ]
    labels = ["Branch", "HEAD", "Status"]
    parts: list[str] = []
    for label, cmd in zip(labels, commands):
        try:
            proc = subprocess.run(
                cmd,
                cwd=str(workdir),
                env=env,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                timeout=5,
                check=False,
            )
        except Exception:
            continue
        value = proc.stdout.strip()
        if value:
            parts.append(f"{label}:\n{value[:4000]}")
    return "\n\n".join(parts)


def _fable_config(config: dict[str, Any] | None) -> dict[str, Any]:
    if config is None:
        try:
            from hermes_cli.config import load_config

            config = load_config()
        except Exception:
            config = {}
    section = config.get("fable") if isinstance(config, dict) else {}
    return section if isinstance(section, dict) else {}


def _positive_int(value: Any, default: int) -> int:
    try:
        parsed = int(value)
        if parsed > 0:
            return parsed
    except Exception:
        pass
    return default


def _error(message: str) -> FablePlanResult:
    return FablePlanResult(False, "", FABLE_TRANSPORT, FABLE_MODEL, message)
