"""Plan-only Claude Fable 5 runner for Hermes slash commands."""

from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any


FABLE_PROVIDER = "anthropic"
FABLE_MODEL = "claude-fable-5"
FABLE_ROUTE = "anthropic_oauth"
FABLE_TRANSPORT = "anthropic_oauth"
FABLE_REASONING = {"enabled": True, "effort": "high"}

FABLE_PLAN_SYSTEM_PROMPT = """You are Claude Fable 5 running inside Hermes as a plan-only command.

Generate a Markdown implementation plan only. Do not edit files, create branches,
open pull requests, deploy, or claim that any implementation has happened.

The plan must include these sections:
- Goal
- Current Context and Assumptions
- Proposed Approach
- Step-by-Step Plan
- Files Likely to Change
- Tests and Validation
- Risks and Open Questions

State clearly that this is a plan generated by Claude Fable 5 via Hermes `/fable`.
Keep the plan concrete and actionable, but do not include fabricated completion
status, commits, PRs, deployments, or test results.
"""


@dataclass(frozen=True)
class FablePlanRequest:
    prompt: str
    session_id: str = ""
    workdir: str = ""
    source_text: str = ""
    platform: str = ""
    transport: str = FABLE_TRANSPORT
    max_tokens: int = 12000
    timeout_seconds: int = 300


@dataclass(frozen=True)
class FablePlanResult:
    ok: bool
    content: str
    transport: str
    model: str
    error: str = ""
    refusal: bool = False


def fable_metadata(result: FablePlanResult | None = None) -> dict[str, Any]:
    metadata = {
        "command": "fable",
        "plan_artifact_kind": "fable_plan",
        "response_kind": "fable_plan",
        "kind": "fable_plan",
        "transport": FABLE_TRANSPORT,
        "provider": FABLE_PROVIDER,
        "model": FABLE_MODEL,
    }
    if result is not None:
        metadata["transport"] = result.transport
        metadata["model"] = result.model
        metadata["ok"] = result.ok
        metadata["refusal"] = result.refusal
    return metadata


def build_fable_context_packet(request: FablePlanRequest) -> str:
    sections = [
        ("User Request", request.prompt.strip()),
        ("Plan-Only Contract", "Generate a Markdown plan only. Do not edit files, open PRs, deploy, or claim implementation."),
        ("Session", request.session_id.strip()),
        ("Platform", request.platform.strip()),
        ("Workdir", request.workdir.strip()),
        ("Source Text", request.source_text.strip()),
    ]

    workdir = Path(request.workdir).expanduser() if request.workdir else None
    if workdir and workdir.exists() and workdir.is_dir():
        sections.extend(_workspace_context_sections(workdir))

    rendered: list[str] = []
    for title, value in sections:
        if value:
            rendered.append(f"## {title}\n{value.strip()}")
    return "\n\n".join(rendered).strip()


def generate_fable_plan(request: FablePlanRequest, config: dict[str, Any] | None = None) -> FablePlanResult:
    cfg = _fable_config(config)
    if cfg.get("enabled") is False:
        return _error("/fable is disabled in Hermes config.")
    if str(cfg.get("provider") or FABLE_PROVIDER).strip().lower() != FABLE_PROVIDER:
        return _error("/fable is pinned to provider=anthropic; configured provider is unsupported.")
    if str(cfg.get("model") or FABLE_MODEL).strip() != FABLE_MODEL:
        return _error("/fable is pinned to model=claude-fable-5; configured model is unsupported.")
    if str(cfg.get("route") or FABLE_ROUTE).strip().lower() != FABLE_ROUTE:
        return _error("/fable is pinned to route=anthropic_oauth; configured route is unsupported.")
    if request.transport != FABLE_TRANSPORT:
        return _error("/fable only supports Hermes' Anthropic OAuth route.")

    max_tokens = _positive_int(cfg.get("max_tokens"), request.max_tokens)
    timeout_seconds = _positive_int(cfg.get("timeout_seconds"), request.timeout_seconds)
    return _generate_via_anthropic_oauth(
        FablePlanRequest(
            prompt=request.prompt,
            session_id=request.session_id,
            workdir=request.workdir,
            source_text=request.source_text,
            platform=request.platform,
            transport=request.transport,
            max_tokens=max_tokens,
            timeout_seconds=timeout_seconds,
        )
    )


def _generate_via_anthropic_oauth(request: FablePlanRequest) -> FablePlanResult:
    preflight_error = _anthropic_budget_preflight_error()
    if preflight_error:
        return _error(preflight_error)

    try:
        from agent.auxiliary_client import resolve_provider_client

        client, resolved_model = resolve_provider_client(FABLE_PROVIDER, FABLE_MODEL)
    except Exception as exc:
        return _error(f"Fable 5 is not configured through Hermes' Anthropic OAuth route: {exc}")

    if client is None or not resolved_model:
        route_error = _anthropic_budget_preflight_error()
        if route_error:
            return _error(route_error)
        return _error(
            "Fable 5 is not configured through Hermes' Anthropic OAuth route. "
            "Run `hermes auth add anthropic` or configure the Anthropic OAuth provider used by Hermes."
        )
    if str(resolved_model) != FABLE_MODEL:
        return _error(f"Fable route resolved unexpected model {resolved_model!r}; refusing to fall back.")

    try:
        response = client.chat.completions.create(
            model=FABLE_MODEL,
            messages=[
                {"role": "system", "content": FABLE_PLAN_SYSTEM_PROMPT},
                {"role": "user", "content": build_fable_context_packet(request)},
            ],
            max_tokens=request.max_tokens,
            timeout=request.timeout_seconds,
            extra_body={"reasoning": FABLE_REASONING},
        )
    except Exception as exc:
        if _is_fable_budget_error(exc):
            return _error(_fable_budget_error_message(str(exc)))
        return _error(f"Fable 5 request failed on Hermes' Anthropic OAuth route: {exc}")

    response_model = str(getattr(response, "model", "") or "")
    if response_model and response_model != FABLE_MODEL:
        return _error(
            f"Fable route returned unexpected model {response_model!r}; refusing to treat a fallback model as Fable output."
        )

    choice = (getattr(response, "choices", None) or [None])[0]
    finish_reason = str(getattr(choice, "finish_reason", "") or "").lower()
    content = _extract_choice_content(choice).strip()
    if finish_reason == "refusal":
        return FablePlanResult(False, content, FABLE_TRANSPORT, FABLE_MODEL, "Fable refused this request.", refusal=True)
    if not content or len(content) < 40:
        return _error("Fable 5 returned an empty or too-short plan; refusing to post junk output.")
    return FablePlanResult(True, _ensure_plan_disclaimer(content), FABLE_TRANSPORT, FABLE_MODEL)


def _is_fable_budget_error(exc: Exception) -> bool:
    """Return True for Anthropic/Fable budget, quota, billing, or credit exhaustion.

    `/fable` is intentionally pinned to Claude Fable 5. If that route reports
    budget exhaustion, the command must fail closed instead of using the general
    auxiliary provider/model fallback machinery.
    """
    try:
        from agent.auxiliary_client import _is_payment_error

        if _is_payment_error(exc):
            return True
    except Exception:
        pass

    status = getattr(exc, "status_code", None)
    text = str(exc).lower()
    if status == 402:
        return True
    return any(
        marker in text
        for marker in (
            "budget expended",
            "budget is expended",
            "budget exhausted",
            "budget is exhausted",
            "quota exceeded",
            "quota_exceeded",
            "daily quota",
            "daily limit",
            "weekly usage limit",
            "weekly limit",
            "resource exhausted",
            "no usable credits",
            "insufficient funds",
            "payment required",
            "balance_depleted",
            "out of funds",
            "run out of funds",
            "not available on the free tier",
            "model_not_supported_on_free_tier",
        )
    )


def _fable_budget_error_message(detail: str = "") -> str:
    base = (
        "Fable 5 budget/quota is expended on Hermes' Anthropic OAuth route; "
        "/fable is pinned to claude-fable-5 and will not fall back to another model or provider."
    )
    cleaned = " ".join(str(detail or "").split())[:500]
    if cleaned:
        return f"{base} Provider detail: {cleaned}"
    return base


def _anthropic_budget_preflight_error() -> str:
    """Surface already-known Anthropic pool exhaustion before trying fallbacks.

    The credential pool can know that every Anthropic OAuth credential is in an
    exhausted cooldown before the request starts. In that case `/fable` should
    return a terminal Fable-specific error, not a generic "route unavailable"
    that invites later code to try another model/provider.
    """
    try:
        from agent.credential_pool import STATUS_DEAD, STATUS_EXHAUSTED, load_pool

        pool = load_pool(FABLE_PROVIDER)
        if not pool.has_credentials() or pool.has_available():
            return ""
        entries = pool.entries()
    except Exception:
        return ""

    exhausted = [entry for entry in entries if getattr(entry, "last_status", None) == STATUS_EXHAUSTED]
    if exhausted:
        return _fable_budget_error_message(_summarize_pool_exhaustion(exhausted[0]))

    dead = [entry for entry in entries if getattr(entry, "last_status", None) == STATUS_DEAD]
    if dead and len(dead) == len(entries):
        return (
            "All configured Anthropic OAuth credentials are marked permanently unavailable; "
            "/fable is pinned to claude-fable-5 and will not fall back to another model or provider. "
            "Re-authenticate Anthropic before using `/fable` again."
        )

    return (
        "No selectable Anthropic OAuth credential is available for `/fable`; "
        "/fable is pinned to claude-fable-5 and will not fall back to another model or provider."
    )


def _summarize_pool_exhaustion(entry: Any) -> str:
    parts: list[str] = []
    code = getattr(entry, "last_error_code", None)
    reason = getattr(entry, "last_error_reason", None)
    message = getattr(entry, "last_error_message", None)
    reset_at = getattr(entry, "last_error_reset_at", None)
    if code:
        parts.append(f"status={code}")
    if reason:
        parts.append(f"reason={reason}")
    if reset_at:
        parts.append(f"reset_at={reset_at}")
    if message:
        parts.append(str(message))
    return "; ".join(parts)


def _extract_choice_content(choice: Any) -> str:
    message = getattr(choice, "message", None)
    content = getattr(message, "content", "") if message is not None else ""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts: list[str] = []
        for item in content:
            if isinstance(item, dict):
                text = item.get("text") or item.get("content")
                if isinstance(text, str):
                    parts.append(text)
        return "".join(parts)
    return str(content or "")


def _ensure_plan_disclaimer(content: str) -> str:
    marker = "Generated by Claude Fable 5 via Hermes `/fable`. This is a plan only; no implementation was performed."
    if "no implementation" in content.lower() or "plan only" in content.lower():
        return content.strip()
    return f"{content.strip()}\n\n> {marker}"


def _workspace_context_sections(workdir: Path) -> list[tuple[str, str]]:
    sections: list[tuple[str, str]] = []
    for rel in ("AGENTS.md", "docs/project-state.md", "docs/context.md"):
        path = workdir / rel
        if path.is_file():
            sections.append((rel, _read_excerpt(path)))
    git_summary = _git_summary(workdir)
    if git_summary:
        sections.append(("Git Summary", git_summary))
    return sections


def _read_excerpt(path: Path, limit: int = 6000) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    return text[:limit]


def _git_summary(workdir: Path) -> str:
    if not (workdir / ".git").exists():
        return ""
    env = os.environ.copy()
    env.pop("GIT_DIR", None)
    env.pop("GIT_WORK_TREE", None)
    commands = [
        ["git", "rev-parse", "--abbrev-ref", "HEAD"],
        ["git", "rev-parse", "--short", "HEAD"],
        ["git", "status", "--short"],
    ]
    labels = ["Branch", "HEAD", "Status"]
    parts: list[str] = []
    for label, cmd in zip(labels, commands):
        try:
            proc = subprocess.run(
                cmd,
                cwd=str(workdir),
                env=env,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                timeout=5,
                check=False,
            )
        except Exception:
            continue
        value = proc.stdout.strip()
        if value:
            parts.append(f"{label}:\n{value[:4000]}")
    return "\n\n".join(parts)


def _fable_config(config: dict[str, Any] | None) -> dict[str, Any]:
    if config is None:
        try:
            from hermes_cli.config import load_config

            config = load_config()
        except Exception:
            config = {}
    section = config.get("fable") if isinstance(config, dict) else {}
    return section if isinstance(section, dict) else {}


def _positive_int(value: Any, default: int) -> int:
    try:
        parsed = int(value)
        if parsed > 0:
            return parsed
    except Exception:
        pass
    return default


def _error(message: str) -> FablePlanResult:
    return FablePlanResult(False, "", FABLE_TRANSPORT, FABLE_MODEL, message)
