"""Fork-owned configuration defaults layered onto upstream Hermes.

Keep fork-specific defaults here so future upstream config merges can take the
new upstream schema wholesale, then add only the local behavior that upstream
does not define. Common-key overrides are deliberately small and document
behavior the fork depends on operationally.
"""

from __future__ import annotations

import copy
from typing import Any

FORK_DEFAULT_ADDITIONS = {
    # Built-ins live exclusively in hermes_cli.model_tiers. This config section
    # is reserved for genuinely custom tier names.
    "model_tiers": {},
    "projects": {},
    "client_knowledge": {
        "intake": {
            "enabled": False,
            "db_path": "",
            "spool_path": "",
            "lease_seconds": 300,
            "max_attempts": 3,
            "retry_delay_seconds": 60,
        },
        "extraction": {
            "enabled": False,
            "derived_path": "",
            "max_jobs_per_run": 10,
            "lease_seconds": 300,
            "retry_delay_seconds": 60,
            "max_message_bytes": 16 * 1024 * 1024,
            "max_part_bytes": 4 * 1024 * 1024,
            "max_total_decoded_bytes": 16 * 1024 * 1024,
            "max_mime_parts": 512,
            "max_mime_depth": 20,
            "max_header_chars": 32_000,
            "max_segment_chars": 300_000,
            "max_output_chars": 600_000,
            "max_document_bytes": 32 * 1024 * 1024,
            "max_zip_members": 1024,
            "max_zip_member_bytes": 8 * 1024 * 1024,
            "max_zip_expanded_bytes": 32 * 1024 * 1024,
            "max_zip_compression_ratio": 100,
            "max_document_output_chars": 300_000,
            "max_notebook_cells": 2000,
            "max_notebook_source_items": 5000,
            "max_xlsx_sheets": 64,
            "max_xlsx_rows_per_sheet": 5000,
            "max_xlsx_cols": 256,
            "max_xlsx_shared_strings": 100_000,
        },
        "interpretation": {
            "enabled": False,
            "max_jobs_per_run": 10,
            "lease_seconds": 300,
            "retry_delay_seconds": 60,
            "timeout_seconds": 180,
            "max_tokens": 8192,
            "max_input_chars": 600_000,
            "max_output_bytes": 1_000_000,
        },
        "notion": {
            "enabled": False,
            "api_key_env": "NOTION_API_KEY",
            "request_timeout_seconds": 30,
            "max_file_bytes": 0,
            "multipart_part_bytes": 10 * 1024 * 1024,
            "max_jobs_per_run": 10,
            "lease_seconds": 300,
            "claim_heartbeat_seconds": 30,
        },
        "gmail": {
            "enabled": False,
            "mailbox": "",
            "token_path": "",
            "poll_interval_seconds": 120,
            "request_timeout_seconds": 30,
            "reconcile_lookback_days": 14,
            "max_reconcile_messages": 500,
            "historical_processing": "disabled",
            "max_message_bytes": 64 * 1024 * 1024,
            "max_http_response_bytes": 96 * 1024 * 1024,
            "max_header_bytes": 256 * 1024,
            "max_header_count": 2000,
            "max_header_line_bytes": 64 * 1024,
            "max_mime_parts": 512,
            "max_mime_depth": 20,
            "max_attachments": 100,
            "max_attachment_bytes": 32 * 1024 * 1024,
            "max_total_attachment_bytes": 64 * 1024 * 1024,
            "mime_parse_timeout_seconds": 30,
            "mime_parser_memory_bytes": 256 * 1024 * 1024,
            "mime_parser_cpu_seconds": 20,
            "max_consistent_invalid_raw_attempts": 3,
            "server_clock_skew_seconds": 300,
        },
    },
    "plugins": {
        "entries": {
            "client-knowledge-gbrain": {
                "llm": {
                    "allowed_model_tiers": ["advanced"],
                },
            },
        },
    },
    "agent": {
        "codex_app_server_turn_timeout": 1800,
        "provider_no_progress_timeout": 900,
        "model_verbosity": "",
        "tool_output_token_limit": "",
        "visual_qa": {
            "mode": "shadow",
            "max_receipts_per_turn": 1,
            "max_followup_turns": 1,
            "max_attempts": 2,
            "max_assertions": 6,
            "max_vision_calls": 2,
            "attempt_timeout_s": 30,
            "total_timeout_s": 60,
            "max_output_chars": 6000,
        },
    },
    "closeout": {
        "mode": "shadow",
        "surfaces": {"kanban": False, "direct": True},
        "early_draft_pr": False,
        "poll_seconds": 30,
        "lease_seconds": 120,
        "max_concurrency": 2,
        "post_merge_requirements": {
            "canonical_sync": False,
            "ci": False,
            "deployment": False,
            "production_qa": False,
            "restart": False,
        },
        "green_unmerged_overdue_seconds": 0,
        "repositories": {},
    },
    "compression": {"summary_ratio": 0.25, "max_summary_tokens": 32000},
    "fable": {
        "enabled": True,
        "provider": "anthropic",
        "model": "claude-fable-5",
        "route": "anthropic_oauth",
        "enabled_toolsets": ["file", "terminal", "web", "browser", "discord"],
        "timeout_seconds": 300,
        "max_tokens": 12000,
        "save_local_plan": False,
    },
    "opus": {
        "enabled": True,
        "provider": "anthropic",
        "model": "claude-opus-5",
        "route": "anthropic_oauth",
        "enabled_toolsets": ["file", "terminal", "web", "browser", "discord"],
        "timeout_seconds": 300,
        "max_tokens": 12000,
        "save_local_plan": False,
    },
    "auxiliary": {
        "vision": {"api_mode": ""},
        "web_extract": {"api_mode": ""},
        "compression": {"api_mode": "", "fallback_chain": []},
        "skills_hub": {"api_mode": ""},
        "approval": {"api_mode": ""},
        "mcp": {"api_mode": ""},
        "title_generation": {"api_mode": ""},
        "feature_summary": {
            "provider": "auto",
            "model": "",
            "base_url": "",
            "api_key": "",
            "api_mode": "",
            "timeout": 15,
            "extra_body": {},
        },
        "feature_summary_triage": {
            "provider": "auto",
            "model": "gpt-5.6-luna",
            "base_url": "",
            "api_key": "",
            "api_mode": "",
            "timeout": 5,
            "reasoning_effort": "none",
            "extra_body": {},
        },
        "foreman_manual_escalation": {
            "provider": "auto",
            "model": "",
            "base_url": "",
            "api_key": "",
            "api_mode": "",
            "timeout": 30,
            "extra_body": {},
        },
        "triage_specifier": {"api_mode": ""},
        "kanban_decomposer": {"api_mode": ""},
        "profile_describer": {"api_mode": ""},
        "curator": {"api_mode": ""},
    },
    "display": {
        "terminal_notify_on_complete": True,
        "background_process_notifications": "all",
        "classic_resize_full_clear": True,
    },
    "dashboard": {"host": "127.0.0.1", "port": 9119},
    "delegation": {"nested_coding": {"enabled": False}},
    "coding_worker": {
        "enabled": True,
        "backend": "codex",
        "inherit_fast_mode": True,
        "model_tier": "",
        "simple_build_model_tier": "intermediate",
        "complex_plan_model_tier": "advanced",
        "complex_build_model_tier": "intermediate",
        "turn_timeout_seconds": 3600,
        "parallel": {"enabled": True, "max_workers": 3},
        "background": {"enabled": True, "max_concurrent": 3},
        "simple_build_reasoning_level": "medium",
        "complex_plan_reasoning_level": "xhigh",
        "complex_build_reasoning_level": "medium",
        "opencode": {
            "binary": "opencode",
            "model": "hermes-codex/gpt-5.6-sol",
            "plan_agent": "plan",
            "build_agent": "build",
            "dangerously_skip_permissions": False,
            "isolated_config": True,
            "startup_timeout_seconds": 90,
        },
    },
    "ui_work": {
        "enabled": True,
        "detection": {
            "action_keywords": [
                "implement",
                "implementing",
                "build",
                "building",
                "create",
                "creating",
                "add",
                "adding",
                "develop",
                "developing",
                "development",
                "design",
                "designing",
                "redesign",
                "redesigning",
                "style",
                "styling",
                "restyle",
                "polish",
                "polishing",
                "visual design",
                "make responsive",
            ],
            "non_visual_domain_keywords": [
                "state",
                "app-state",
                "application state",
                "routing",
                "route",
                "router",
                "data",
                "dataset",
                "datasets",
                "config",
                "configuration",
                "default",
                "defaults",
                "selection",
                "selection model",
                "normalization",
                "normalize",
                "normalized",
                "plumbing",
                "wiring",
                "model",
                "models",
                "schema",
                "store",
                "storage",
                "query",
                "queries",
                "api",
                "backend",
                "server",
                "database",
                "db",
                "endpoint",
                "endpoints",
                "contract",
                "serialization",
                "parser",
                "ingestion",
                "pipeline",
            ],
            "visual_intent_keywords": [
                "style",
                "styling",
                "restyle",
                "polish",
                "polishing",
                "visual design",
                "visual polish",
                "ui polish",
                "interface polish",
                "layout polish",
                "visual",
                "visuals",
                "appearance",
                "css",
                "responsive",
                "spacing",
                "color",
                "colors",
                "typography",
                "theme",
                "design system",
            ],
            "visual_surface_keywords": [
                "web ui",
                "web interface",
                "app interface",
                "user interface",
                "interface design",
                "visual design",
                "visual polish",
                "ui polish",
                "interface polish",
                "layout polish",
                "visual",
                "visuals",
                "appearance",
                "styling",
                "styles",
                "css",
                "responsive",
                "spacing",
                "color",
                "typography",
                "theme",
                "design system",
                "component",
                "card",
                "footer",
                "header",
                "sidebar",
                "toolbar",
                "modal",
                "drawer",
                "button",
                "form",
                "chart",
                "labels",
                "table",
            ],
            "negative_keywords": [
                "tui",
                "terminal",
                "terminal-rendering",
                "terminal rendering",
                "terminal ui",
                "cli",
                "command-line",
                "command line",
                "shell",
                "tty",
                "pty",
                "ink",
                "curses",
                "prompt_toolkit",
                "repaint",
                "backend-only",
                "backend only",
                "api-only",
                "api only",
                "server-only",
                "server only",
                "backend",
                "api",
                "server",
                "database",
                "db",
                "schema",
                "migration",
                "cron",
                "scheduler",
                "runtime",
                "auth",
                "authentication",
                "no frontend",
                "not frontend",
                "no ui",
                "not ui",
                "non-ui",
                "without ui",
                "without frontend",
                "review",
                "reviewing",
                "look at",
                "looking at",
                "inspect",
                "inspecting",
                "inspection",
                "audit",
                "assess",
                "evaluate",
                "monitor",
                "smoke",
                "verify",
                "validation",
                "screenshot",
                "visual check",
                "test",
                "tests",
                "pytest",
                "unit test",
                "regression",
                "docs",
                "documentation",
                "readme",
                "changelog",
                "pr",
                "pull request",
                "merge",
                "ci",
                "follow-up",
                "follow up",
                "review comment",
                "review feedback",
            ],
        },
        # Explicit visual implementation work gets one read-only Opus design
        # consultation before the normal Codex/OpenCode coding worker. Set
        # false to keep detection advisory-only.
        "route_delegate_task": True,
    },
    "skills": {"index": {"workers": "focus", "debug": False}},
    "worktrees": {
        "dependency_reuse": {"pnpm": True, "python_venv": True},
        "cleanup": {
            "enabled": True,
            "retention_days": 7,
            "min_interval_hours": 24,
            "action_retention_minutes": 15,
            "action_min_interval_minutes": 5,
            "max_per_run": 25,
        },
    },
    "discord": {
        "action_request_channels": "",
        "feature_request_channels": "",
        "action_request_model_tier": "discord_action",
        "read_only_model_tier": "discord_read_only",
        "action_request_reasoning_effort": "medium",
        "feature_request_reasoning_effort": "medium",
        "action_worktree_warmup": "auto",
        "action_worktree_warmup_timeout_seconds": 180,
        "project_channel_cwd": "",
        "channel_cwds": {},
        "project_mapping_ignored_channel_names": "",
        "project_mapping_ignored_category_names": "",
        "voice_auto_tag": False,
        "history_backfill_feature_channels": False,
        "feature_summary_triage_timeout": 5,
    },
    "cron": {
        "model_tier": "trivial",
        "memory_mode": "off",
        "missed_run_grace_seconds": 300,
    },
    "self_improvement": {
        "proposal_contract_version": "self_improvement.proposal_run.v1",
        "default_max_cards_per_run": 5,
        "feedback_context": {
            "enabled": True,
            "max_items_per_kind": 3,
            "max_text_chars": 180,
        },
        "projects": {
            "hermes": {
                "label": "Hermes",
                "description": "Hermes #dev self-improvement proposals.",
                "discord_channel_id": "",
                "discord_channel_name": "#dev",
                "source_hint": "#dev",
                "prongs": {
                    "daily-retrospective": {
                        "label": "Daily Retrospective",
                        "focus": "Hermes daily retrospective findings and recommendations that can become discrete operator-improvement tasks.",
                        "max_cards_per_run": 5,
                    },
                    "system-doctor": {
                        "label": "System Doctor",
                        "focus": "Hermes runtime health, gateway reliability, worker orchestration, and operational diagnostics.",
                        "max_cards_per_run": 5,
                    },
                    "discord_execution_audit": {
                        "label": "Daily Discord execution audit",
                        "focus": "One actionable Hermes system bottleneck derived from the previous local calendar day's structured Discord execution evidence, or zero cards when the evidence is smooth, weak, ambiguous, or duplicated.",
                        "max_cards_per_run": 1,
                    },
                },
            },
            "pid": {
                "label": "PID",
                "description": "Sligo PID operator self-improvement proposals.",
                "discord_channel_id": "",
                "prongs": {
                    "airflow_scraper_doctor": {
                        "label": "Nightly PID Airflow scraper doctor",
                        "focus": "Airflow scraper reliability, observability, and source-ingestion maintenance.",
                        "max_cards_per_run": 5,
                    },
                    "admin_dogfood_ux_bugfix": {
                        "label": "Daily PID admin dogfood UX bugfix",
                        "focus": "Admin dogfood issues that can become discrete UX bugfix tasks.",
                        "max_cards_per_run": 5,
                    },
                    "invisible_technical_recommendations": {
                        "label": "Daily PID invisible technical recommendations",
                        "focus": "Backend, infrastructure, data quality, and maintainability improvements invisible to end users.",
                        "max_cards_per_run": 5,
                    },
                    "visible_ui_ux_recommendations": {
                        "label": "Daily PID visible UI/UX recommendations",
                        "focus": "User-facing PID interface improvements with clear operator or customer value.",
                        "max_cards_per_run": 5,
                    },
                },
            },
        },
    },
    "kanban": {
        "auto_subscribe_on_create": True,
        "discord_intake": {"default_board_channels": ""},
        "discord_worker": {
            "public_base_url": "",
            "backend": "",
            "runner": "host",
            "docker_image": "ghcr.io/nousresearch/hermes-codex-worker:latest",
            "docker_bin": "docker",
            "codex_home_root": "",
            "excluded_workspaces": [
                "/home/droid/workspaces/hermes-self-improvement-live-test"
            ],
            "service_tier": "auto",
            "max_global_workers": 8,
            "max_workers_per_board": 2,
            "max_dev_workers_per_board": 1,
            "review_loop_limit": 5,
            "task_threads": {"enabled": True},
            "foreman": {
                "enabled": False,
                "channel_id": "1504252294495998043",
                "mention": "<@&1503914570077442058>",
                "master_board": "default",
                "scan_interval_seconds": 30,
                "blocked_board_min_age_seconds": 600,
                "cooldown_seconds": 3600,
                "retry_backoff_seconds": 300,
                "max_retry_backoff_seconds": 3600,
                "retention_seconds": 30 * 24 * 3600,
                "max_alerts_per_tick": 10,
                "max_alerts_per_board_per_day": 20,
                "min_board_created_at": 0,
                "terminal_suppression_age_seconds": 7 * 24 * 3600,
            },
            "roles": {
                "planner": {
                    "model_tier": "advanced",
                    "service_tier": "auto",
                    "max_runtime_seconds": 1800,
                },
                "dev": {
                    "model_tier": "intermediate",
                    "service_tier": "auto",
                    "max_runtime_seconds": 3600,
                },
                "foreman": {
                    "model_tier": "advanced",
                    "service_tier": "auto",
                    "max_runtime_seconds": 1800,
                },
                "reviewer": {
                    "model_tier": "advanced",
                    "service_tier": "auto",
                    "max_runtime_seconds": 1800,
                },
            },
        },
    },
    "logging": {"memory_monitor": {"enabled": True, "interval_seconds": 300}},
    "gateway": {"model_tier": "basic"},
}

FORK_DEFAULT_OVERRIDES: dict[str, Any] = {
    # Preserve the fork's explicit-human approval posture while adopting
    # upstream smart classification and unconditional deny-rule support.
    "approvals": {"mode": "manual"},
    # Long Discord development turns and graceful operator restarts are
    # established fork behavior. Domain verification may narrow these later.
    "agent": {
        "max_turns": 1000,
        "restart_drain_timeout": 180,
    },
    # The fork deliberately compresses later; preserve that fidelity budget
    # while adopting upstream in-place and Codex-aware compression modes.
    "compression": {"threshold": 0.70},
    # Multi-bot project threads must continue requiring an inline mention.
    "discord": {"thread_require_mention": True},
    # Discord intent triage is latency-sensitive and returns one short label;
    # keep it on the fast model with reasoning disabled even if upstream adds
    # its own defaults for the same auxiliary task.
    "auxiliary": {
        "feature_summary_triage": {
            "model": "gpt-5.6-luna",
            "reasoning_effort": "none",
            "timeout": 5,
        },
    },
    # The fork's Discord action flow expects edit-based response streaming.
    "streaming": {"enabled": True},
    # Keep worker-board pickup responsive for the development workflow.
    "kanban": {"dispatch_interval_seconds": 5},
}


def _fill_missing(base: dict[str, Any], additions: dict[str, Any]) -> None:
    """Recursively add keys that upstream does not already define."""
    for key, value in additions.items():
        if key not in base:
            base[key] = copy.deepcopy(value)
        elif isinstance(base[key], dict) and isinstance(value, dict):
            _fill_missing(base[key], value)


def _apply_overrides(base: dict[str, Any], overrides: dict[str, Any]) -> None:
    """Recursively apply the narrow defaults the fork intentionally owns."""
    for key, value in overrides.items():
        if isinstance(value, dict):
            target = base.setdefault(key, {})
            if not isinstance(target, dict):
                base[key] = copy.deepcopy(value)
            else:
                _apply_overrides(target, value)
        else:
            base[key] = copy.deepcopy(value)


def apply_fork_defaults(default_config: dict[str, Any]) -> None:
    """Mutate default_config with fork additions and intentional overrides."""
    _fill_missing(default_config, FORK_DEFAULT_ADDITIONS)
    _apply_overrides(default_config, FORK_DEFAULT_OVERRIDES)
